### ISSUE TITLE
Possible to make it able to change weather api from accuweather?

### ISSUE THREAD

**Issue by Ud4ba** [geometric-weather-foss/GeometricWeather#15]
The accuracy is the only minus on this app . can you do it?

**Comment by papjul** [comment]
In which country do you find the weather to be inaccurate?
What other free API do you suggest?

**Comment by Ud4ba** [comment]
At Greece . The accuracy is 100% off . Im not so sure , i would like to see openweatherman api .
I dont think so Greece has its own api . http://www.emy.gr/emy/en/ , or here : https://meteo.gr/ are the main sites for weather at greece .

**Comment by UnsolvedCypher** [comment]
I think OpenWeatherMap's API is generally pretty good for most locations around the world. It is also probably more privacy-friendly than AccuWeather. Could this be included as a source, or would that have to be done upstream? I think it would bring a significant improvement in accuracy to a number of users.

**Comment by papjul** [comment]
This fork is only to remove closed sources dependencies and be able to make a release for F-Droid. Although I'm working on a way to make this work directly upstream through build flavors. I'm however a bit hopeless here as a similar pull request few years ago never got merged.

I made an other weather provider originally on this fork but now I submitted it upstream and am waiting for approval. If it is accepted, I would be happy to try (with no guarantee) implementing OpenWeatherMap API upstream as another weather provider. Otherwise, it would be difficult to maintain the weather provider only on this fork. The maintenance process of the patches for F-Droid is already time-consuming.

As a side note, there was an issue 3 years ago upstream mentioning OpenWeatherMap would be implemented soon: https://github.com/WangDaYeeeeee/GeometricWeather/issues/55 I don't think it's still in the works but you should probably continue the discussion related to OpenWeatherMap there.

**Comment by UnsolvedCypher** [comment]
Ok thank you for all of the information! I wasn't sure what was going on upstream since it looks like some PRs have been hanging out for a while. I've bumped the issue you mentioned and hopefully will get an update. Thanks for your effort with the Météo France source- I saw that but didn't realize it was you!

**Comment by UnsolvedCypher** [comment]
@papjul Since your upstream PR for Météo was approved, is OpenWeatherMap support still something you'd be interested in trying to implement?

**Comment by papjul** [comment]
Yes, it is.
But there is still some work to do on the F-Droid build before so I can work on a clean base.
Then, I need to find the time to implement it. While it's not very complicated to do, it's a very time-consuming task.

**Comment by mbestavros** [comment]
@Ud4ba @UnsolvedCypher The upstream app now has two alternative APIs in OpenWeatherMap and Meteo France, and, additionally, is available on F-Droid [here](https://f-droid.org/en/packages/wangdaye.com.geometricweather/).

Given the above, and the fact this fork is no longer supported, I'm closing this issue.
